INSERT INTO USERS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.GENDER
FROM jsoren.PUBLIC_USER_INFORMATION U
WHERE TRUE

INSERT INTO 


INSERT INTO CITIES SELECT DISTINCT U.CURRENT_CITY, U.CURRENT_STATE, U.CURRENT_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION U
UNION SELECT DISTINCT E.EVENT_CITY, E.EVENT_STATE, E.EVENT_COUNTRY
FROM jsoren.PUBLIC_EVENT_INFORMATION E


INSERT INTO USER_CURRENT_CITIES SELECT DISTINCT U.USER_ID, U.CURRENT_CITIES
FROM jsoren.PUBLIC_USER_INFORMATION U

INSERT INTO USER_HOMETOWN_CITIES SELECT DISTINCT U.USER_ID, U.HOMETOWN_CITIES
FROM jsoren.PUBLIC_USER_INFORMATION U

INSERT INTO PROGRAMS SELECT DISTINCT U.INSTITUTION_NAME, U.PROGRAM_CONCENTRATION, U.PROGRAM_DEGREE
FROM jsoren.PUBLIC_USER_INFORMATION U

INSERT INTO EDUCATION SELECT DISTINCT U.USER_ID, U.PROGRAM_YEAR
FROM jsoren.PUBLIC_USER_INFORMATION U

INSERT INTO ALBUM SELECT DISTINCT P.ALBUM_ID, P.OWNER_ID, P.ALBUM_NAME, P.ALBUM_CREATED_TIME, P.ALBUM_MODIFIED_TIME, P.ALBUM_LINK, P.ALBUM_VISIBILITY, P.COVER_PHOTO_ID
FROM jsoren.PUBLIC_PHOTO_INFORMATION P

INSERT INTO PHOTO SELECT DISTINCT P.PHOTO_ID, P.ALBUM_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM jsoren.PUBLIC_PHOTO_INFORMATION P

INSERT INTO TAGS SELECT DISTINCT T.PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X_COORDINATE, T.TAG_Y_COORDINATE
FROM jsoren.PUBLIC_TAG_INFORMATION T

INSERT INTO USER_EVENT SELECT DISTINCT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_ID, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM jsoren.PUBLIC_EVENT_INFORMATION E, CITIES C
WHERE E.EVENT_CITY = C.CITY_NAME AND E.EVENT_STATE = C.STATE_NAME AND E.EVENT_COUNTRY = C.COUNTRY_NAME
