INSERT INTO USERS 
SELECT DISTINCT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, U.GENDER
FROM jsoren.PUBLIC_USER_INFORMATION U;

INSERT INTO FRIENDS
SELECT DISTINCT F.USER1_ID, F.USER2_ID
FROM jsoren.PUBLIC_ARE_FRIENDS F;

INSERT INTO CITIES(CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT U.CURRENT_CITY, U.CURRENT_STATE, U.CURRENT_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION U
UNION
SELECT DISTINCT U.HOMETOWN_CITY, U.HOMETOWN_STATE, U.HOMETOWN_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION U
UNION
SELECT DISTINCT E.EVENT_CITY, E.EVENT_STATE, E.EVENT_COUNTRY
FROM jsoren.PUBLIC_EVENT_INFORMATION E;

INSERT INTO USER_CURRENT_CITIES
SELECT DISTINCT U.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION U, CITIES C
WHERE U.CURRENT_CITY = C.CITY_NAME AND U.CURRENT_STATE = C.STATE_NAME AND U.CURRENT_COUNTRY = C.COUNTRY_NAME;

INSERT INTO USER_HOMETOWN_CITIES
SELECT DISTINCT U.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION U, CITIES C
WHERE U.HOMETOWN_CITY = C.CITY_NAME AND U.HOMETOWN_STATE = C.STATE_NAME AND U.HOMETOWN_COUNTRY = C.COUNTRY_NAME;

INSERT INTO PROGRAMS(INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT U.INSTITUTION_NAME, U.PROGRAM_CONCENTRATION, U.PROGRAM_DEGREE
FROM jsoren.PUBLIC_USER_INFORMATION U
WHERE U.INSTITUTION_NAME != NULL AND U.PROGRAM_CONCENTRATION != NULL AND U.PROGRAM_DEGREE != NULL;

INSERT INTO EDUCATION
SELECT DISTINCT U.USER_ID, P.PROGRAM_ID, U.PROGRAM_YEAR
FROM jsoren.PUBLIC_USER_INFORMATION U, PROGRAMS P
WHERE P.INSTITUTION = U.INSTITUTION_NAME AND P.CONCENTRATION = U.PROGRAM_CONCENTRATION AND P.DEGREE = U.PROGRAM_DEGREE;

INSERT INTO ALBUMS
SELECT DISTINCT P.ALBUM_ID, P.OWNER_ID, P.ALBUM_NAME, P.ALBUM_CREATED_TIME, P.ALBUM_MODIFIED_TIME, P.ALBUM_LINK, P.ALBUM_VISIBILITY, P.COVER_PHOTO_ID
FROM jsoren.PUBLIC_PHOTO_INFORMATION P;

INSERT INTO PHOTOS
SELECT DISTINCT P.PHOTO_ID, P.ALBUM_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM jsoren.PUBLIC_PHOTO_INFORMATION P;

INSERT INTO TAGS
SELECT DISTINCT T.PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X_COORDINATE, T.TAG_Y_COORDINATE
FROM jsoren.PUBLIC_TAG_INFORMATION T;

INSERT INTO USER_EVENTS
SELECT DISTINCT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_ID, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM jsoren.PUBLIC_EVENT_INFORMATION E, CITIES C
WHERE E.EVENT_CITY = C.CITY_NAME AND E.EVENT_STATE = C.STATE_NAME AND E.EVENT_COUNTRY = C.COUNTRY_NAME;

COMMIT;